### ISSUE TITLE
ES: level ignored for numeric input

### ISSUE THREAD

**Issue by mariusbommert** [GeoBosh/cvar#2]
In the ES function, the level x seems to be ignored for numeric inputs. In the following example both levels of x lead to the same results:
```{R}
library(cvar)
ES(1:100, x = 0.05) 
# -3
ES(1:100, x = 0.01)
# -3
```
It seems necessary to update the following part of the function:
```{R}
if (is.numeric(dist)) {
  v <- VaR.numeric(dist, x = 0.05, ..., intercept = intercept, 
                   slope = slope)
  bad <- dist[dist <= -v]
  res <- -mean(bad)
  return(res)
}
```
Here x = x is required instead of x = 0.05:
```{R}
if (is.numeric(dist)) {
  v <- VaR.numeric(dist, x = x, ..., intercept = intercept, 
                   slope = slope)
  bad <- dist[dist <= -v]
  res <- -mean(bad)
  return(res)
}
```

**Comment by GeoBosh** [comment]
Thanks for the detailed report and the fix. I have implemented it and will submit v0.4.1 to CRAN shortly.
